add_newline = false
#right_format = "$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch[  â–‘â–’â–“â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–‡â–†â–…â–„â–ƒâ–‚â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”](#ff80ff)"

#format = "$character[â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–“â–’â–‘  ](#ff80ff)$directory$cmd_duration$line_break "
#format = "[  â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”](#ff80ff)[â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–“â–’â–‘  ](#ff80ff)$directory$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$cmd_duration$character$line_break "
#format = "[  â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”](#ff00ff)$directory$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$cmd_duration$character$line_break "
format = "$fill$directory$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$cmd_duration$character$line_break "
# [  â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”â–”](#000000)

[character]
error_symbol = "[â¨¯](bold red)"
success_symbol = "[âœ“](bold green)"
format = "$symbol"

[directory]
truncation_length = 5
style = "#000000"
#format = "[$path]($style)[$lock_symbol]($lock_style) "

#format = "[$path](#ff00ff)($style)[â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–‡â–†â–…â–„â–ƒâ–‚â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”](#ff80ff)[$lock_symbol]($lock_style) "
#format = "[â–¬â–¬Î¹â•â•â•â•â•â•â•ïº¤  $path  -â•â•â•â•â•â•â•Î¹â–¬â–¬](#ff00ff)($style)[$lock_symbol]($lock_style) "
#format = "[â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–“â–’â–‘  ](#808080)[$path](#800080)($style)[  â–‘â–’â–“â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”](#808080)[$lock_symbol]($lock_style) "
#[â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”ğŸ®‚ğŸ®ƒâ–€ğŸ®„ğŸ®…ğŸ®†â–ˆâ–‡â–†â–…â–„â–ƒâ–‚â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆğŸ®†ğŸ®…ğŸ®„â–€ğŸ®ƒğŸ®‚â–”](#ff80ff)

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold gray"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "${count}âœˆï¸ "
behind = "${count}ğŸ‘´ "
diverged = "â‰  ${ahead_count}âœˆï¸ ${behind_count}ğŸ‘´ "
untracked = "${count}ğŸ¤¦â€â™€ï¸ "
stashed = "ğŸ "
modified = "${count}âœï¸ "
staged = "${count}ğŸ‘€ "
renamed = "${count}å "
deleted = "${count}ğŸ—‘ï¸ "
style = "bright-gray"
format = "$all_status$ahead_behind"

[cmd_duration]
#min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "[â‰ˆ$duration]($style) "

[fill]
symbol = "â–”"
style = "#000000"
